########################################
### REGISTRAR USUÁRIO ADMIN
POST http://127.0.0.1:8000/auth/register
Content-Type: application/json

{
  "nome": "Admin10",
  "email": "admin10@email.com",
  "senha": "123456",
  "role": "admin"
}

###

########################################
### LOGIN (PEGAR TOKEN)
POST http://127.0.0.1:8000/auth/login
Content-Type: application/json

{
  "email": "admin10@email.com",
  "senha": "123456"
}

###

########################################
### 👇 COLE O TOKEN DO LOGIN AQUI
@token = @token = <COLE_AQUI_O_TOKEN_DO_LOGIN>


########################################
### CRUD MANGÁS

### LISTAR MANGÁS (público)
GET http://127.0.0.1:8000/mangas/

###

### TESTE ADMIN (somente admin)
POST http://127.0.0.1:8000/mangas/teste-admin
Authorization: Bearer {{token}}

###

### CRIAR MANGÁ (admin)
POST http://127.0.0.1:8000/mangas/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "titulo": "btoom!",
  "autor": "Junya Inoue",
  "genero": "Ação, Suspense",
  "volumes": 26,
  "status": "Completo",
  "descricao": "Manga sobre um jogo de sobrevivência em uma ilha deserta."
}

###

### ATUALIZAR MANGÁ (admin)
PUT http://127.0.0.1:8000/mangas/9
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "descricao": "Atualizado via testes"
}

###

### DELETAR MANGÁ (admin)
DELETE http://127.0.0.1:8000/mangas/9
Authorization: Bearer {{token}}

###

########################################
### CRUD LIVROS

### LISTAR LIVROS
GET http://127.0.0.1:8000/livros/

###

### CRIAR LIVRO (admin)
POST http://127.0.0.1:8000/livros/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "titulo": "Cabal",
  "autor": "Clive Barker",
  "descricao": "Um romance de horror que explora os limites entre a realidade e o sobrenatural.",
  "ano": 1991,
  "genero": "Horror, Fantasia"
}

###

########################################
### FAVORITOS - MANGÁS

### ADICIONAR MANGÁ AOS FAVORITOS
POST http://127.0.0.1:8000/favoritos/manga/7
Authorization: Bearer {{token}}

###

### LISTAR FAVORITOS DE MANGÁS
GET http://127.0.0.1:8000/favoritos/manga/
Authorization: Bearer {{token}}

###

### REMOVER MANGÁ DOS FAVORITOS
DELETE http://127.0.0.1:8000/favoritos/manga/5
Authorization: Bearer {{token}}

###

########################################
### FAVORITOS - LIVROS

### ADICIONAR LIVRO NOS FAVORITOS
POST http://127.0.0.1:8000/favoritos/livros/8
Authorization: Bearer {{token}}

###

### LISTAR FAVORITOS DE LIVROS
GET http://127.0.0.1:8000/favoritos/livros/
Authorization: Bearer {{token}}

###

### REMOVER LIVRO DOS FAVORITOS
DELETE http://127.0.0.1:8000/favoritos/livros/2
Authorization: Bearer {{token}}
###
