########################################
### REGISTRAR USUÁRIO ADMIN
POST http://127.0.0.1:8000/auth/register
Content-Type: application/json

{
  "nome": "Admin3",
  "email": "admin3@email.com",
  "senha": "123456",
  "role": "admin"
}


########################################
### LOGIN (PEGAR TOKEN ADMIN)
POST http://127.0.0.1:8000/auth/login
Content-Type: application/json

{
  "email": "admin3@email.com",
  "senha": "123456"
}

########################################
### COLE O TOKEN DO LOGIN AQUI 👇
@token = @token = <COLE_AQUI_O_TOKEN_DO_LOGIN>




########################################
### TESTE CRUD - MANGÁS

### LISTAR MANGÁS (qualquer usuário)
GET http://127.0.0.1:8000/mangas/


### TESTE ADMIN (somente admin)
POST http://127.0.0.1:8000/mangas/teste-admin
Authorization: Bearer {{token}}


### CRIAR MANGÁ (somente admin)
POST http://127.0.0.1:8000/mangas/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "titulo": "Naruto",
  "autor": "Masashi Kishimoto",
  "genero": "Shounen",
  "volumes": 72,
  "status": "Concluído",
  "descricao": "Mangá clássico sobre ninjas"
}



### ATUALIZAR MANGÁ (somente admin)
PUT http://127.0.0.1:8000/mangas/2
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "titulo": "Naruto Shippuden",
  "descricao": "Agora mais forte"
}


### DELETAR MANGÁ (somente admin)
DELETE http://127.0.0.1:8000/mangas/2
Authorization: Bearer {{token}}


########################################
### TESTE CRUD - LIVROS

### LISTAR LIVROS (público)
GET http://127.0.0.1:8000/livros/


### CRIAR LIVRO (admin)
POST http://127.0.0.1:8000/livros/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "titulo": "Livro Python",
  "autor": "Guido van Rossum",
  "descricao": "Aprenda Python do zero",
  "ano": 2024,
  "genero": "Tecnologia"
}

########################################
### FAVORITOS - MANGÁS (usuário autenticado)

### ADICIONAR FAVORITO
POST http://127.0.0.1:8000/favoritos/mangas?manga_id=1
Authorization: Bearer {{token}}


### LISTAR FAVORITOS
GET http://127.0.0.1:8000/favoritos/mangas/
Authorization: Bearer {{token}}


### REMOVER FAVORITO
DELETE http://127.0.0.1:8000/favoritos/mangas/1
Authorization: Bearer {{token}}
