"""sprint3 constraints cascades timestamps capa

Revision ID: 96cef16a19bf
Revises: 9adbf8f1dfa7
Create Date: 2026-08-14 20:30:36.405303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96cef16a19bf'
down_revision: Union[str, Sequence[str], None] = '9adbf8f1dfa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('livros', sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_column('livros', 'capa_livro')
    op.create_unique_constraint('uq_manga_volumes_manga_numero', 'manga_volumes', ['manga_id', 'numero'])
    op.drop_constraint(op.f('manga_volumes_manga_id_fkey'), 'manga_volumes', type_='foreignkey')
    op.create_foreign_key(op.f('manga_volumes_manga_id_fkey'), 'manga_volumes', 'mangas', ['manga_id'], ['id'], ondelete='CASCADE')
    op.add_column('mangas', sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('mangas', sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('usuarios', sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('usuarios', sa.Column('ativo', sa.Boolean(), server_default='true', nullable=False))
    op.alter_column('usuarios_favoritos_livros', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('usuarios_favoritos_livros', 'livro_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint('uq_favorito_livro_usuario_livro', 'usuarios_favoritos_livros', ['usuario_id', 'livro_id'])
    op.drop_constraint(op.f('usuarios_favoritos_livros_usuario_id_fkey'), 'usuarios_favoritos_livros', type_='foreignkey')
    op.drop_constraint(op.f('usuarios_favoritos_livros_livro_id_fkey'), 'usuarios_favoritos_livros', type_='foreignkey')
    op.create_foreign_key(op.f('usuarios_favoritos_livros_livro_id_fkey'), 'usuarios_favoritos_livros', 'livros', ['livro_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('usuarios_favoritos_livros_usuario_id_fkey'), 'usuarios_favoritos_livros', 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')
    op.alter_column('usuarios_favoritos_mangas', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('usuarios_favoritos_mangas', 'manga_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint('uq_favorito_manga_usuario_manga', 'usuarios_favoritos_mangas', ['usuario_id', 'manga_id'])
    op.drop_constraint(op.f('usuarios_favoritos_mangas_usuario_id_fkey'), 'usuarios_favoritos_mangas', type_='foreignkey')
    op.drop_constraint(op.f('usuarios_favoritos_mangas_manga_id_fkey'), 'usuarios_favoritos_mangas', type_='foreignkey')
    op.create_foreign_key(op.f('usuarios_favoritos_mangas_usuario_id_fkey'), 'usuarios_favoritos_mangas', 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('usuarios_favoritos_mangas_manga_id_fkey'), 'usuarios_favoritos_mangas', 'mangas', ['manga_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('usuarios_favoritos_mangas_manga_id_fkey'), 'usuarios_favoritos_mangas', type_='foreignkey')
    op.drop_constraint(op.f('usuarios_favoritos_mangas_usuario_id_fkey'), 'usuarios_favoritos_mangas', type_='foreignkey')
    op.create_foreign_key(op.f('usuarios_favoritos_mangas_manga_id_fkey'), 'usuarios_favoritos_mangas', 'mangas', ['manga_id'], ['id'])
    op.create_foreign_key(op.f('usuarios_favoritos_mangas_usuario_id_fkey'), 'usuarios_favoritos_mangas', 'usuarios', ['usuario_id'], ['id'])
    op.drop_constraint('uq_favorito_manga_usuario_manga', 'usuarios_favoritos_mangas', type_='unique')
    op.alter_column('usuarios_favoritos_mangas', 'manga_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('usuarios_favoritos_mangas', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('usuarios_favoritos_livros_livro_id_fkey'), 'usuarios_favoritos_livros', type_='foreignkey')
    op.drop_constraint(op.f('usuarios_favoritos_livros_usuario_id_fkey'), 'usuarios_favoritos_livros', type_='foreignkey')
    op.create_foreign_key(op.f('usuarios_favoritos_livros_livro_id_fkey'), 'usuarios_favoritos_livros', 'livros', ['livro_id'], ['id'])
    op.create_foreign_key(op.f('usuarios_favoritos_livros_usuario_id_fkey'), 'usuarios_favoritos_livros', 'usuarios', ['usuario_id'], ['id'])
    op.drop_constraint('uq_favorito_livro_usuario_livro', 'usuarios_favoritos_livros', type_='unique')
    op.alter_column('usuarios_favoritos_livros', 'livro_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('usuarios_favoritos_livros', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('usuarios', 'ativo')
    op.drop_column('usuarios', 'criado_em')
    op.drop_column('mangas', 'atualizado_em')
    op.drop_column('mangas', 'criado_em')
    op.drop_constraint(op.f('manga_volumes_manga_id_fkey'), 'manga_volumes', type_='foreignkey')
    op.create_foreign_key(op.f('manga_volumes_manga_id_fkey'), 'manga_volumes', 'mangas', ['manga_id'], ['id'])
    op.drop_constraint('uq_manga_volumes_manga_numero', 'manga_volumes', type_='unique')
    op.add_column('livros', sa.Column('capa_livro', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('livros', 'atualizado_em')
    # ### end Alembic commands ###
