"""baseline schema

Revision ID: baa3815000af
Revises: 
Create Date: 2026-08-14 14:43:03.810239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baa3815000af'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('livros',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('autor', sa.String(length=255), nullable=False),
    sa.Column('genero', sa.String(length=100), nullable=False),
    sa.Column('isbn', sa.String(length=20), nullable=True),
    sa.Column('data_publicacao', sa.Date(), nullable=True),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('sinopse', sa.Text(), nullable=True),
    sa.Column('capa_url', sa.String(length=500), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('capa_livro', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isbn')
    )
    op.create_index(op.f('ix_livros_id'), 'livros', ['id'], unique=False)
    op.create_table('mangas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('autor', sa.String(length=255), nullable=False),
    sa.Column('artista', sa.String(length=255), nullable=True),
    sa.Column('genero', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('data_lancamento', sa.Date(), nullable=True),
    sa.Column('sinopse', sa.Text(), nullable=True),
    sa.Column('capa_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mangas_id'), 'mangas', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('manga_volumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manga_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('comprado', sa.Boolean(), nullable=True),
    sa.Column('capa_volume', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['manga_id'], ['mangas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manga_volumes_id'), 'manga_volumes', ['id'], unique=False)
    op.create_table('usuarios_favoritos_livros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('livro_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['livro_id'], ['livros.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_favoritos_livros_id'), 'usuarios_favoritos_livros', ['id'], unique=False)
    op.create_table('usuarios_favoritos_mangas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('manga_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['manga_id'], ['mangas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_favoritos_mangas_id'), 'usuarios_favoritos_mangas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_favoritos_mangas_id'), table_name='usuarios_favoritos_mangas')
    op.drop_table('usuarios_favoritos_mangas')
    op.drop_index(op.f('ix_usuarios_favoritos_livros_id'), table_name='usuarios_favoritos_livros')
    op.drop_table('usuarios_favoritos_livros')
    op.drop_index(op.f('ix_manga_volumes_id'), table_name='manga_volumes')
    op.drop_table('manga_volumes')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_mangas_id'), table_name='mangas')
    op.drop_table('mangas')
    op.drop_index(op.f('ix_livros_id'), table_name='livros')
    op.drop_table('livros')
    # ### end Alembic commands ###
